// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoLimitTexasHoldemV2.Data;

#nullable disable

namespace NoLimitTexasHoldemV2.Migrations
{
    [DbContext(typeof(PokerContext))]
    partial class PokerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NoLimitTexasHoldemV2.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"));

                    b.Property<int?>("CommunityHandDataId")
                        .HasColumnType("int");

                    b.Property<int?>("MachineHandDataId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerHandDataId")
                        .HasColumnType("int");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardId");

                    b.HasIndex("CommunityHandDataId");

                    b.HasIndex("MachineHandDataId");

                    b.HasIndex("PlayerHandDataId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("NoLimitTexasHoldemV2.Models.HandData", b =>
                {
                    b.Property<int>("HandDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HandDataId"));

                    b.Property<int>("Bet")
                        .HasColumnType("int");

                    b.Property<DateTime>("HandDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MachineHandRank")
                        .HasColumnType("int");

                    b.Property<int>("MachineInitialStack")
                        .HasColumnType("int");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerHandRank")
                        .HasColumnType("int");

                    b.Property<int>("PlayerInitialStack")
                        .HasColumnType("int");

                    b.HasKey("HandDataId");

                    b.ToTable("Hands");
                });

            modelBuilder.Entity("NoLimitTexasHoldemV2.Models.Card", b =>
                {
                    b.HasOne("NoLimitTexasHoldemV2.Models.HandData", "CommunityHandData")
                        .WithMany("CommunityCards")
                        .HasForeignKey("CommunityHandDataId");

                    b.HasOne("NoLimitTexasHoldemV2.Models.HandData", "MachineHandData")
                        .WithMany("MachineHoleCards")
                        .HasForeignKey("MachineHandDataId");

                    b.HasOne("NoLimitTexasHoldemV2.Models.HandData", "PlayerHandData")
                        .WithMany("PlayerHoleCards")
                        .HasForeignKey("PlayerHandDataId");

                    b.Navigation("CommunityHandData");

                    b.Navigation("MachineHandData");

                    b.Navigation("PlayerHandData");
                });

            modelBuilder.Entity("NoLimitTexasHoldemV2.Models.HandData", b =>
                {
                    b.Navigation("CommunityCards");

                    b.Navigation("MachineHoleCards");

                    b.Navigation("PlayerHoleCards");
                });
#pragma warning restore 612, 618
        }
    }
}
